# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f886b85f670118d4f40173f5af77f8e247738e3f229d938041c78d47f2d520086c292e7ece59e781db376125be639ed07daed07129d9a6b52bff0e0da8f55f8f

test:
  secret_key_base: 14cbe2cefa1c333782cf693fd4df8f00df0144aca6d7a436a7a9abc6bb7f37b18b42c283527bb67d4071dc21f99e205eedb2beb48aebfa5aaa8aff900610fccd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
